import json
from pathlib import Path
from book_research import enrich

ROOT = Path(__file__).parent
sources = {
 'project-ajk': {'id':'project-ajk','title':'AJK Biradari Localities Directory','author':'Project artwork','date':'Current supplied version, inspected 7 October 2026','kind':'Project material','url':'assets/ajk-directory.png','image':True,'limitation':'A selected working directory. Its locality examples and affiliations need individual references. All motifs are decorative.'},
 'project-clans': {'id':'project-clans','title':'Major Rajput Clans of Pakistan','author':'Project artwork','date':'Current supplied version, inspected 7 October 2026','kind':'Project material','url':'assets/rajput-clans.png','image':True,'limitation':'The inventory includes Rajput-associated and disputed classifications. Symbols and locality examples are not independently authenticated here.'},
 'ibbetson': {'id':'ibbetson','title':'Panjab Castes','author':'Denzil Ibbetson','date':'1881 census account, first published 1883; reprinted 1916','kind':'Historical source','url':'https://archive.org/details/panjabcastes00ibbe','textUrl':'https://archive.org/stream/panjabcastes00ibbe/panjabcastes00ibbe_djvu.txt','limitation':'A colonial census text, with period-specific categories and prejudicial language. It documents recorded usage, not a final genealogy or current population distribution. OCR can contain errors.'},
 'hrw': {'id':'hrw','title':'With Friends Like These','author':'Human Rights Watch','date':'2006','kind':'Regional context','url':'https://www.hrw.org/reports/2006/pakistan0906/3.htm','limitation':'Use the Background chapter for the specific regional descriptions cited. Its historical estimates and administrative divisions are not current statistics. It does not establish lineage.'}
}

records=[]
def add(id,name,regions,type,classification,places,summary,caution,aliases=None,context=None,question=None):
    project='project-ajk' if type!='clan' else 'project-clans'
    aliases=aliases or []
    claims=[]
    if context:
        claims.append({'title':'Recorded usage','text':context['text'],'status':'context','source':context['source'],'locator':context['locator']})
    claims.append({'title':'Classification and locality scope','text':caution,'status':'verify','source':project,'locator':name+' panel and the poster footer'})
    records.append({'id':id,'name':name,'regions':regions,'type':type,'classification':classification,'aliases':aliases,'locations':places,'locationSource':project,'summary':summary,'caution':caution,'hasContext':bool(context),'claims':claims,'sourceIds':list(dict.fromkeys(([context['source']] if context else [])+[project])),'question':question or 'Find a district or family-specific reference for the classification and locality examples before using them as historical facts.'})

def alias(name,kind='Project spelling',note='The project pairs these spellings. This is a search link, not proof of shared ancestry.'):
    return {'name':name,'kind':kind,'note':note}
def book(text,locator): return {'source':'ibbetson','text':text,'locator':locator}
def hrw(text): return {'source':'hrw','text':text,'locator':'II Background, Culture and ethnicity'}

add('gujjar','Gujjar',['kashmir'],'community','Community identity in the AJK directory',['Muzaffarabad division','Poonch division','Mirpur division'],'The AJK project directory includes Gujjar as a community identity. An independent regional account also names Gujjars in AJK.','The poster examples span divisions. They do not establish exclusive areas, current population size or one genealogy.',[alias('Gujjars','Spelling in regional source')],hrw('HRW names Gujjars among AJK biradaris.'),'Verify district-specific locality examples. Keep any population estimate dated and attributed.')
add('jat','Jat',['kashmir'],'community','Community identity in the AJK directory',['Mirpur','Bhimber','Kotli'],'Jat appears in the AJK directory, paired with Jutt. The independent context used here concerns Mirpuri Jats.','The regional reference supports Mirpuri usage. Bhimber and Kotli remain locality examples from the project poster.',[alias('Jutt'),alias('Jats','Plural in regional source')],hrw('HRW describes Mirpuri Jats in southern AJK.'),'Find a local reference for each district. Do not treat the wider Jat identity as one clan.')
add('rajput','Rajput',['kashmir'],'community','Broader identity in the AJK directory',['Across AJK'],'The project uses Rajput as a broader community identity. Individual clan records are catalogued separately.','The broad label does not settle the affiliation or genealogy of every named clan. The collection follows the supplied poster scope.',[alias('Rajputs','Plural in regional source')],hrw('HRW describes Rajputs across AJK.'),'Qualify each clan association individually instead of applying the broad label to every family.')
add('sudhan','Sudhan',['kashmir'],'community','Community identity in the AJK directory',['Poonch','Sudhanoti','Bagh','Kotli'],'The AJK directory includes Sudhan. Independent regional context places Sudhans in the southeastern part of AJK.','The poster names four district examples. Any Pashtun or Sadozai ancestry statement needs a separate attributed source and scope.',[alias('Sudhans','Plural in regional source')],hrw('HRW associates Sudhans with Bagh and Rawalakot in Poonch.'),'Verify the additional locality examples and find the source for any lineage tradition before adding it.')
add('mughal','Mughal',['kashmir'],'community','Community label in the AJK directory',['Bagh','Muzaffarabad'],'Mughal is a named community entry in the project directory. The current record preserves its locality examples as research leads.','The directory alone does not establish Central Asian descent or a relationship to the imperial Mughal dynasty.',question='Find a specific AJK reference for the recorded identity and localities. Keep dynasty and family identity separate.')
add('awan','Awan',['kashmir'],'community','Community identity in the AJK directory',['Muzaffarabad','Hattian Bala','Bagh','Poonch'],'Awan appears in the project directory. Its AJK locality examples remain open for more specific sourcing.','A historic Punjab reference cannot by itself confirm these AJK examples or a claimed common ancestor.',context=book('Ibbetson includes Awan in his regional classification.','Part IV, section 465, Awan, Caste No 12'))
add('abbasi','Abbasi',['kashmir'],'title','Lineage identity in the project directory',['Bagh','Hattian Bala','Muzaffarabad'],'The AJK poster lists Abbasi. This record retains the supplied name without merging it with another community.','The name alone does not authenticate Abbasid descent. Any equivalence with Dhund needs local and source-specific support.',question='Check the intended local community, its name variants and any claimed relationship to Dhund.')
add('syed','Syed',['kashmir'],'title','Lineage identity in the project directory',['Bhimber'],'Syed is included in the project directory with Bhimber as an example locality. Family-level claims remain outside the evidence of this poster.','A lineage title alone does not prove the ancestry of a particular family. The Bhimber example needs its own reference.',question='Find a locality-specific source. Attribute any family genealogy to the evidence that records it.')
add('khawaja','Khawaja',['kashmir'],'title','Name or title in the project directory',['Muzaffarabad'],'The directory includes Khawaja with a Muzaffarabad locality example. Its precise use as a title or community label needs confirmation.','A shared name or title is insufficient to establish a single clan or common ancestor.',question='Check whether this entry denotes a title, a local community or a family name in the cited locality.')

clans=[
 ('bhatti','Bhatti',['punjab'],['Lahore','Gujranwala','Sialkot','Faisalabad'],'Rajput-associated in the project chart',[],book('Ibbetson discusses Bhatti within his Rajput entries.','Part III, The Bhatti, No 2'),'A Rajput association does not prove that all Bhatti families share one lineage. The Jaisalmer device in the poster is not authenticated for every family.'),
 ('chauhan','Chauhan',['punjab'],['Attock','Chakwal','Jhelum'],'Rajput-associated in the project chart',[alias('Chohan')],book('Ibbetson discusses Chauhan among Rajput entries.','Part III, The Chauhan, No 2'),'Keep the historical category attributed. The project locality examples and the proposed emblem need separate documentation.'),
 ('janjua','Janjua',['punjab'],['Rawalpindi','Jhelum','Chakwal'],'Rajput-associated in the project chart',[],book('Ibbetson discusses Janjua among western hill Rajputs.','Part III, section 454, Janjua, No 8'),'The classification records a source context. Raja Mal or Rathor descent requires an attributed lineage account, not an inference from the name.'),
 ('chibb','Chibb',['punjab','kashmir'],['Bhimber (AJK)','Gujrat (Punjab)','Sialkot (Punjab)'],'Rajput-associated in the project chart',[alias('Chib'),alias('Chibh','Historical source spelling','Ibbetson uses Chibh. Check the specific family and locality when connecting historical and modern spellings.')],book('Ibbetson includes a Chibh entry under Jammu-border Rajputs.','Part III, section 455, The Chibh, No 10'),'The historic entry reports origin claims. It does not establish the Katoch ancestry of every family using a related spelling.'),
 ('gakhar','Gakhar',['punjab'],['Rawalpindi','Hazara (outside current browsing scope)'],'Classification needs source-specific treatment',[alias('Gakkar'),alias('Gakkhar','Historical source spelling')],book('Ibbetson treats Gakkhar in a separate tribal entry.','Part IV, The Gakkhar entry'),'The project chart groups Gakhar with Rajput-associated names. That grouping does not settle its classification. Hazara is retained only as an out-of-scope poster example.'),
 ('minhas','Minhas',['punjab','kashmir'],['Mirpur (AJK)','Kotli (AJK)','Gujrat (Punjab)','Sialkot (Punjab)'],'Rajput-associated in the project chart',[alias('Manhas')],book('Ibbetson discusses Manhas among Jammu-border Rajputs.','Part III, section 455, The Manhas, No 9'),'Historical Manhas usage does not establish a universal equivalence for every Minhas family. Solar descent remains a tradition requiring attribution.'),
 ('naru','Naru',['punjab'],['Southern Punjab'],'Rajput-associated in the project chart',[alias('Narwa','Unconfirmed project label','The poster pairs Narwa with Naru. That relationship has not been independently verified.')],book('Ibbetson records Naru around Jalandhar and Hoshiarpur.','Part III, Naru entry preceding The Ghorewaha, No 13'),'The independent context concerns a different part of historical Punjab. The southern Punjab example and Narwa pairing need verification.'),
 ('sial','Sial',['punjab'],['Jhang','Sargodha','Multan'],'Rajput-associated in the project chart',[],book('Ibbetson records Sial in a Jhang-related entry.','Part III, The Sial, No 8'),'Origin narratives and relationships with other groups remain attributed traditions. The shared name does not establish every branch genealogy.'),
 ('tiwana','Tiwana',['punjab'],['Khushab','Mianwali'],'Rajput-associated in the project chart',[],book('Ibbetson discusses Tiwana and Mitha Tiwana.','Part III, Tiwana passage near the Ranjha entry'),'The history of a chiefly family and a community-wide lineage are separate claims. The poster motif is not an authenticated universal emblem.'),
 ('ranjha','Ranjha',['punjab'],['Mandi Bahauddin','Gujrat'],'Classification varies in the project chart',[],book('Ibbetson includes Ranjha under Rajput tribes of the Jhelum.','Part III, section 451, The Ranjha, No 9'),'A period-specific classification should not replace local family identification. These locality examples need contemporary or district-specific support.'),
 ('jasgam','Jasgam',['punjab'],['Rawalpindi','Islamabad'],'Rajput-associated in the project chart',[],None,'The spelling and classification currently come from the poster. No independent entry has been resolved here. A missing OCR match does not prove absence.'),
 ('jasra','Jasra',['punjab'],['Rawalpindi'],'Rajput-associated in the project chart',[],None,'The present record is a research lead. Confirm the exact spelling and a local reference before connecting it to a lineage.'),
 ('khokhar','Khokhar',['punjab'],['Lahore','Sheikhupura','Central Punjab'],'Classification varies in the project chart',[],book('Ibbetson records Khokhar under differing Rajput and Jat returns.','Part IV, section 468, The Khokhar'),'Retain the locality and date of the classification. Keep Khokhar and Gakhar separate; similar names do not justify merging records.'),
 ('dogar','Dogar',['punjab'],['Faisalabad','Toba Tek Singh','Okara'],'Rajput association disputed in the project chart',[alias('Dogan','Unconfirmed project label','Dogan appears in the poster. It is not accepted here as a verified Dogar spelling.')],book('Ibbetson questions the Dogar Rajput-origin claim.','Part IV, Dogar entry'),'The ancestry claim remains disputed. The Dogan label and the listed modern locality examples require independent verification.')
]
for id,name,regions,places,classification,aliases,context,caution in clans:
    add(id,name,regions,'clan',classification,places,f'{name} appears in the project clan chart. '+('An independent historical passage provides context for the recorded name or classification.' if context else 'This entry currently serves as a research lead.'),caution,aliases,context)

book_metadata = enrich(records, sources)
payload={'version':2,'checkedOn':'8 October 2026','scope':'Selected Pakistani Punjab and AJK records, with dated examples from wider historical Punjab','sources':sources,'records':records,'book':book_metadata}
(ROOT/'dist/data.js').write_text('window.COLLECTION = '+json.dumps(payload,ensure_ascii=False,indent=2)+';\n',encoding='utf-8',newline='\n')
print(f'Prepared {len(records)} records and {len(sources)} source items')
